[package]
name = "rigscribe"
version = "0.1.0"
edition = "2024"

[dependencies]

rig-core = {version="0.26.0",features=["all"]}
serde = { version = "1.0.228", features = ["derive"] }
termimad = "0.34.1"
thiserror = "2.0.17"
tokio = {version= "1.48.0",features=["full"]}
